package database

import (
	"gorm.io/gorm"

	"github.com/panxiangyu1995/AI-Automated-office/api/internal/model"
)

func SystemModels() []interface{} {
	return []interface{}{
		&model.Group{},
		&model.Enterprise{},
		&model.User{},
		&model.DeviceCode{},
		&model.Role{},
		&model.Permission{},
		&model.RolePermission{},
		&model.EmployeePermissionABAC{},
		&model.PermissionAttr{},
		&model.CustomRule{},
		&model.EmployeePermission{},
		&model.CrossEnterprisePermission{},
		&model.Department{},
		&model.Employee{},
		&model.Position{},
		&model.Customer{},
		&model.CustomerLevel{},
		&model.CustomerTag{},
		&model.Contact{},
		&model.Opportunity{},
		&model.Supplier{},
		&model.Material{},
		&model.Warehouse{},
		&model.WarehouseInventory{},
		&model.StockFlow{},
		&model.MaterialPrice{},
		&model.InventoryCheck{},
		&model.InventoryCheckItem{},
		&model.PurchaseOrder{},
		&model.PurchaseOrderItem{},
		&model.SalesOrder{},
		&model.SalesOrderItem{},
		&model.TransferOrder{},
		&model.Requisition{},
		&model.Contract{},
		&model.ContractReference{},
		&model.ContractAttachment{},
		&model.ServiceOrder{},
		&model.PaymentRecord{},
		&model.ExpenseRecord{},
		&model.Invoice{},
		&model.WfDefinition{},
		&model.WfInstance{},
		&model.WfApproval{},
		&model.FileMetadata{},
		&model.FileRecord{},
		&model.Message{},
		&model.Announcement{},
		&model.AnnouncementReadStatus{},
		&model.KnowledgeDoc{},
		&model.VectorRecord{},
		&model.DocChunk{},
		&model.ChatSession{},
		&model.ChatMessage{},
		&model.KBCategory{},
		&model.Skill{},
		&model.SkillRoleOpening{},
		&model.SkillParameter{},
		&model.FieldDefinition{},
		&model.RelationDefinition{},
		&model.AuditLog{},
		&model.AuditLogEntry{},
		&model.SubscriptionPlan{},
		&model.EnterpriseSubscription{},
		&model.Webhook{},
		&model.ServiceTicket{},
		&model.UsageBill{},
		&model.ServiceConfig{},
		&model.ApiQuota{},
		&model.FeatureFlag{},
		&model.RateLimitConfig{},
		&model.BackupConfig{},
		&model.BackupRecord{},
		&model.ExportTask{},
		&model.ExportHistory{},
		&model.PaymentRequest{},
		&model.CollectionRecord{},
		&model.PaymentPlan{},
		&model.RepairOrder{},
		&model.AlertRule{},
		&model.Receivable{},
		&model.Payable{},
		&model.QualityInspection{},
		&model.QualityInspectionItem{},
		&model.BillingRecord{},
		&model.PaymentGatewayConfig{},
		&model.MFAConfig{},
		&model.UndoOperation{},
		&model.IndustryTemplate{},
		&model.EnterpriseSkillMatrix{},
		&model.ClaudeMDTemplate{},
	}
}

func AutoMigrateSystem(db *gorm.DB) error {
	return db.AutoMigrate(SystemModels()...)
}
