ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT '';
		ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS new_values TEXT;
		ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS old_values TEXT;
		ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT '';
		ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS user_roles TEXT;