ALTER TABLE skills ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE skills ADD COLUMN IF NOT EXISTS method VARCHAR(10) DEFAULT 'POST';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS opening_message TEXT;
ALTER TABLE knowledge_docs ADD COLUMN IF NOT EXISTS version INT DEFAULT 1;
ALTER TABLE knowledge_docs ADD COLUMN IF NOT EXISTS parent_version_id UUID;
ALTER TABLE knowledge_docs ADD COLUMN IF NOT EXISTS visibility VARCHAR(20) DEFAULT 'public';
ALTER TABLE knowledge_docs ADD COLUMN IF NOT EXISTS allowed_department_ids JSONB;
ALTER TABLE knowledge_docs ADD COLUMN IF NOT EXISTS creator_id UUID;
