FROM alpine:3.20

RUN apk update && apk add --no-cache ca-certificates tzdata || (sleep 5 && apk add --no-cache ca-certificates tzdata)

WORKDIR /app

COPY ao-api .
COPY api/config/config.yaml ./config/config.yaml

RUN mkdir -p /app/logs

EXPOSE 8080

CMD ["./ao-api"]
