/**
 * Editor and Template Writeback Module
 * Task 87: Story 49.4 - Editor and Template Writeback
 *
 * Write Agent output into editor and template hosts through controlled contracts.
 *
 * Barrel re-export from sub-modules:
 *  - editorWritebackTypes.ts    (type definitions)
 *  - editorWritebackFactories.ts (ID generation + factories)
 *  - editorWritebackPermissions.ts (permission checking)
 *  - editorWritebackExecution.ts  (execution logic)
 *  - editorWritebackStore.ts     (store + serialization + debug)
 */

export type {
  EditorType,
  TemplateType,
  EditorReference,
  TemplateReference,
  ContentPosition,
  ContentRange,
  TextContentUpdate,
  TemplateSlotRef,
  TemplateContentUpdate,
  EditorState,
  TemplateState,
  EditorWritebackOperationType,
  TemplateWritebackOperationType,
  EditorWritebackOperation,
  TemplateWritebackOperation,
  EditorWritebackAction,
  TemplateWritebackAction,
  EditorWritebackContract,
  TemplateWritebackContract,
  EditorWritebackResult,
  TemplateWritebackResult,
  EditorWritebackOutcome,
  TemplateWritebackOutcome,
  EditorWritebackTrace,
  TemplateWritebackTrace,
  WritebackAuditEntry,
  EditorWritebackStore,
  TemplateWritebackStore,
} from './editorWritebackTypes'

export {
  generateEditorOperationId,
  generateTemplateOperationId,
  generateEditorActionId,
  generateTemplateActionId,
  generateEditorContractId,
  generateTemplateContractId,
  generateEditorTraceId,
  generateTemplateTraceId,
  generateAuditEntryId,
  computeContentHash,
  createEditorReference,
  createTemplateReference,
  createContentPosition,
  createContentRange,
  createTextContentUpdate,
  createTemplateSlotRef,
  createTemplateContentUpdate,
  createEditorState,
  createTemplateState,
  createEditorWritebackOperation,
  createTemplateWritebackOperation,
  createEditorWritebackAction,
  createTemplateWritebackAction,
  createEditorWritebackContract,
  createTemplateWritebackContract,
} from './editorWritebackFactories'

export {
  isEditorTypeAllowed,
  isTemplateTypeAllowed,
  isSlotAllowed,
  checkEditorPermission,
  checkSlotPermission,
  checkContentSize,
  checkLanguage,
} from './editorWritebackPermissions'

export {
  executeEditorOperation,
  executeEditorWriteback,
  executeTemplateOperation,
  executeTemplateWriteback,
} from './editorWritebackExecution'

export {
  createEditorWritebackStore,
  createTemplateWritebackStore,
  registerEditorContract,
  getEditorContract,
  addEditorToStore,
  getEditorFromStore,
  addEditorAction,
  getEditorAction,
  getEditorActionsBySession,
  addEditorOutcome,
  getEditorOutcome,
  addEditorTraces,
  getEditorTraces,
  addEditorAuditEntry,
  registerTemplateContract,
  getTemplateContract,
  addTemplateToStore,
  getTemplateFromStore,
  addTemplateAction,
  getTemplateAction,
  getTemplateActionsBySession,
  addTemplateOutcome,
  getTemplateOutcome,
  addTemplateTraces,
  getTemplateTraces,
  addTemplateAuditEntry,
  serializeEditorRef,
  deserializeEditorRef,
  serializeTemplateRef,
  deserializeTemplateRef,
  serializeEditorState,
  deserializeEditorState,
  serializeTemplateState,
  deserializeTemplateState,
  serializeEditorAction,
  deserializeEditorAction,
  serializeTemplateAction,
  deserializeTemplateAction,
  serializeEditorContract,
  deserializeEditorContract,
  serializeTemplateContract,
  deserializeTemplateContract,
  serializeEditorOutcome,
  deserializeEditorOutcome,
  serializeTemplateOutcome,
  deserializeTemplateOutcome,
  serializeEditorWritebackStore,
  deserializeEditorWritebackStore,
  serializeTemplateWritebackStore,
  deserializeTemplateWritebackStore,
  formatEditorRef,
  formatTemplateRef,
  formatContentRange,
  formatEditorState,
  formatTemplateState,
  formatEditorWritebackResult,
  formatTemplateWritebackResult,
  formatEditorWritebackOutcome,
  formatTemplateWritebackOutcome,
  formatEditorTrace,
  formatTemplateTrace,
} from './editorWritebackStore'
