/**
 * Session Runtime - Writeback Exports
 * Workbench card writeback, editor/template writeback, staged review flow
 */

// Workbench Card Writeback (Task 86: Story 49.3)
export {
  // Types
  type CardSize,
  type CardVisibility,
  type CardStatus,
  type CardContainerReference,
  type CardReference,
  type CardContentType,
  type MetricCardContent,
  type ChartCardContent,
  type ListCardContent,
  type TableCardContent,
  type TextCardContent,
  type ActionCardContent,
  type ImageCardContent,
  type CustomCardContent,
  type WorkbenchCard,
  type CardUpdateOperation,
  type CardWritebackAction,
  type CardWritebackContract,
  type CardWritebackResult,
  type CardWritebackOutcome,
  type CardWritebackTrace,
  type CardWritebackStore,
  type ListItem,

  // ID Generation
  generateCardId,
  generateCardOperationId,
  generateCardActionId,
  generateCardContractId,
  generateCardTraceId,

  // Factory Functions
  createCardContainerReference,
  createCardReference,
  createMetricCardContent,
  createChartCardContent,
  createListCardContent,
  createTableCardContent,
  createTextCardContent,
  createActionCardContent,
  createImageCardContent,
  createCustomCardContent,
  createWorkbenchCard,
  createCardUpdateOperation,
  createCardWritebackAction,
  createCardWritebackContract,

  // Permission Checking
  isContentTypeAllowed,
  checkCardPermission,
  checkVisibilityPermission,
  checkPlacementPermission,

  // Writeback Execution
  executeCardOperation,
  executeCardWriteback,

  // Store Operations
  createCardWritebackStore,
  registerCardContract,
  getCardContract,
  addCardToStore,
  getCardFromStore,
  getCardsByContainer,
  addCardAction,
  getCardAction,
  getCardActionsBySession,
  addCardOutcome,
  getCardOutcome,
  addCardTraces,
  getCardTraces,

  // Serialization
  serializeCardContainerRef,
  deserializeCardContainerRef,
  serializeCardRef,
  deserializeCardRef,
  serializeWorkbenchCard,
  deserializeWorkbenchCard,
  serializeCardAction,
  deserializeCardAction,
  serializeCardContract,
  deserializeCardContract,
  serializeCardOutcome,
  deserializeCardOutcome,
  serializeCardWritebackStore,
  deserializeCardWritebackStore,

  // Debug Formatting
  formatCardContainerRef,
  formatCardRef,
  formatCardContent,
  formatWorkbenchCard,
  formatCardWritebackResult,
  formatCardWritebackOutcome,
  formatCardTrace,
} from './workbenchCardWriteback'

// Editor and Template Writeback (Story 49.4)
export {
  // Types
  type EditorType,
  type TemplateType,
  type EditorReference,
  type TemplateReference,
  type ContentPosition,
  type ContentRange,
  type TextContentUpdate,
  type TemplateSlotRef,
  type TemplateContentUpdate,
  type EditorState,
  type TemplateState,
  type EditorWritebackOperationType,
  type TemplateWritebackOperationType,
  type EditorWritebackOperation,
  type TemplateWritebackOperation,
  type EditorWritebackAction,
  type TemplateWritebackAction,
  type EditorWritebackContract,
  type TemplateWritebackContract,
  type EditorWritebackResult,
  type TemplateWritebackResult,
  type EditorWritebackOutcome,
  type TemplateWritebackOutcome,
  type EditorWritebackTrace,
  type TemplateWritebackTrace,
  type WritebackAuditEntry,
  type EditorWritebackStore,
  type TemplateWritebackStore,

  // ID Generation
  generateEditorOperationId,
  generateTemplateOperationId,
  generateEditorActionId,
  generateTemplateActionId,
  generateEditorContractId,
  generateTemplateContractId,
  generateEditorTraceId,
  generateTemplateTraceId,
  generateAuditEntryId as generateEditorTemplateAuditEntryId,

  // Factory Functions
  createEditorReference,
  createTemplateReference,
  createContentPosition,
  createContentRange,
  createTextContentUpdate,
  createTemplateSlotRef,
  createTemplateContentUpdate,
  createEditorState,
  createTemplateState,
  createEditorWritebackOperation,
  createTemplateWritebackOperation,
  createEditorWritebackAction,
  createTemplateWritebackAction,
  createEditorWritebackContract,
  createTemplateWritebackContract,

  // Permission Checking
  isEditorTypeAllowed,
  isTemplateTypeAllowed,
  isSlotAllowed,
  checkEditorPermission,
  checkSlotPermission,
  checkContentSize,
  checkLanguage,

  // Execution
  executeEditorOperation,
  executeEditorWriteback,
  executeTemplateOperation,
  executeTemplateWriteback,

  // Store Operations
  createEditorWritebackStore,
  createTemplateWritebackStore,
  registerEditorContract,
  getEditorContract,
  addEditorToStore,
  getEditorFromStore,
  addEditorAction,
  getEditorAction,
  getEditorActionsBySession,
  addEditorOutcome,
  getEditorOutcome,
  addEditorTraces,
  getEditorTraces,
  addEditorAuditEntry,
  registerTemplateContract,
  getTemplateContract,
  addTemplateToStore,
  getTemplateFromStore,
  addTemplateAction,
  getTemplateAction,
  getTemplateActionsBySession,
  addTemplateOutcome,
  getTemplateOutcome,
  addTemplateTraces,
  getTemplateTraces,
  addTemplateAuditEntry,

  // Serialization
  serializeEditorRef,
  deserializeEditorRef,
  serializeTemplateRef,
  deserializeTemplateRef,
  serializeEditorState,
  deserializeEditorState,
  serializeTemplateState,
  deserializeTemplateState,
  serializeEditorAction,
  deserializeEditorAction,
  serializeTemplateAction,
  deserializeTemplateAction,
  serializeEditorContract,
  deserializeEditorContract,
  serializeTemplateContract,
  deserializeTemplateContract,
  serializeEditorOutcome,
  deserializeEditorOutcome,
  serializeTemplateOutcome,
  deserializeTemplateOutcome,
  serializeEditorWritebackStore,
  deserializeEditorWritebackStore,
  serializeTemplateWritebackStore,
  deserializeTemplateWritebackStore,

  // Debug Formatting
  formatEditorRef,
  formatTemplateRef,
  formatContentRange,
  formatEditorState,
  formatTemplateState,
  formatEditorWritebackResult,
  formatTemplateWritebackResult,
  formatEditorWritebackOutcome,
  formatTemplateWritebackOutcome,
  formatEditorTrace,
  formatTemplateTrace,
} from './editorTemplateWriteback'

